name: Manually trigger infra deployment

# When this action will be executed
on:
  # Allow mannually trigger 
  workflow_dispatch:      

jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SUPREMEOCTOPALMTREE_AZURE_CREDENTIALS }}

      - name: Create Registry
        uses: azure/arm-deploy@v1
        id: deploy-acr
        with:
          resourceGroupName: supreme-octo-palm-tree-rg
          template: infra/infraacrtemplate.json
          parameters: infra/infraacrparameters.json
          deploymentName: Dev-Env-ACR

      - name: Create App
        uses: azure/arm-deploy@v1
        id: deploy-app
        with:
          resourceGroupName: supreme-octo-palm-tree-rg
          template: infra/infraapptemplate.json
          parameters: infra/infraappparameters.json
          deploymentName: Dev-Env-App