name: Trigger auto deployment for supreme-octo-palm-tree

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/supreme-octo-palm-tree-AutoDeployTrigger-9665ac8f-e48e-427a-ae89-52746d47d770.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: supremeoctopalmtree.azurecr.io
          username: ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_USERNAME }}
          password: ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: supremeoctopalmtree.azurecr.io/supreme-octo-palm-tree:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SUPREMEOCTOPALMTREE_AZURE_CREDENTIALS }}

      - name: Create Registry
        uses: azure/arm-deploy@v1
        id: deploy-acr
        with:
          resourceGroupName: supreme-octo-palm-tree-rg
          template: 'Infra/acr-template.json'
          parameters: 'Infra/acr-parameters.json'
          deploymentName: Dev-Env-ACR

      - name: Create App
        uses: azure/arm-deploy@v1
        id: deploy-app
        with:
          resourceGroupName: supreme-octo-palm-tree-rg
          template: 'Infra/app-template.json'
          parameters: 'Infra/app-parameters.json'
          deploymentName: Dev-Env-App
                
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n supreme-octo-palm-tree -g supreme-octo-palm-tree-rg --server supremeoctopalmtree.azurecr.io --username  ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_USERNAME }} --password ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_PASSWORD }}
            az containerapp update -n supreme-octo-palm-tree -g supreme-octo-palm-tree-rg --image supremeoctopalmtree.azurecr.io/supreme-octo-palm-tree:${{ github.sha }}
