name: Build and deploy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/supreme-octo-palm-tree.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: supremeoctopalmtree.azurecr.io
          username: ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_USERNAME }}
          password: ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: supremeoctopalmtree.azurecr.io/supreme-octo-palm-tree:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          context: ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release was created by '${{ toJSON(github.actor) }}'
          draft: false
          prerelease: false

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    
    steps:

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SUPREMEOCTOPALMTREE_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n supreme-octo-palm-tree -g supreme-octo-palm-tree-rg --server supremeoctopalmtree.azurecr.io --username  ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_USERNAME }} --password ${{ secrets.SUPREMEOCTOPALMTREE_REGISTRY_PASSWORD }}
            az containerapp update -n supreme-octo-palm-tree -g supreme-octo-palm-tree-rg --image supremeoctopalmtree.azurecr.io/supreme-octo-palm-tree:${{ github.sha }}
