name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 6 * * 0'
  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  test:
    name: 'Mocha tests'
    # name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node:
    #       - 14
    #       - 16
    #       - 18
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: '*.json'    # Path to test results
          reporter: mocha-json        # Format of test results