name: Tests
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/supreme-octo-palm-tree.yml'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * 0'
  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  test:
    name: 'Mocha tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: '*.json'    # Path to test results
          reporter: mocha-json        # Format of test results